name: Daily Diaper Deals

on:
  schedule:
    # Runs daily at 4:00 PM UTC (adjust for your timezone)
    ##- cron: '0 6 * * *'
  workflow_dispatch: # Allows manual trigger

jobs:
  find-deals:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Prepare output folder
      run: pwd;mkdir -p artifacts

    - name: Upload diaper deals file
      uses: actions/upload-artifact@v4
      with:
        name: diaper-deals
        path: /home/runner/work/diaper-deal-finder/diaper-deal-finder/artifacts/diaper_everyday_deals.md
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        pip install -r requirements.txt
  
    - name: Run diaper deal finder
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        SERPER_API_KEY: ${{ secrets.SERPER_API_KEY }}
        GMAIL_EMAIL: ${{ secrets.GMAIL_EMAIL }}
        GMAIL_PASSWORD: ${{ secrets.GMAIL_PASSWORD }}
        RECIPIENT_EMAIL: ${{ secrets.RECIPIENT_EMAIL }}
      run: |
        python main.py
        
    - name: Verify completion
      run: |
        if [ -f "diaper_everyday_deals.md" ]; then
          echo "✅ Deals file created and email sent!"
        else
          echo "❌ Something went wrong"
        fi
    - name: Debug file creation
      run: |
        echo "=== DEBUGGING FILE CREATION ==="
        echo "Current directory:"
        pwd
        echo "Directory contents:"
        ls -la
        echo "Looking for ANY .md files:"
        find . -name "*.md" -type f 2>/dev/null || echo "No .md files found anywhere"
        echo "Looking specifically for diaper_everyday_deals.md:"
        find . -name "diaper_everyday_deals.md" -type f 2>/dev/null || echo "diaper_everyday_deals.md not found"
        echo "All files in current directory:"
        ls -la .
        echo "Searching for 'diaper' in filenames:"
        find . -name "*diaper*" -type f 2>/dev/null || echo "No files with 'diaper' in name"
        echo "=== END DEBUG ==="
